# Generated by Django 5.2.5 on 2025-10-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='nick',
            field=models.CharField(db_index=True, error_messages={'blank': 'Informe o apelido.', 'max_length': 'Apelido deve ter no máximo 50 caracteres.'}, max_length=50, unique=True),
        ),
    ]
