# Generated by Django 5.2.5 on 2025-08-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='banner',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='biography',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='language',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='specialties',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
