# Generated by Django 5.2.5 on 2025-08-15 01:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_banner_portfolio_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None),
        ),
    ]
