# Generated by Django 5.2.5 on 2025-08-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('portfolio', '0003_portfolio_categories_portfolio_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='content.video'),
        ),
    ]
