# Generated by Django 5.2.5 on 2025-10-15 12:10

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_videos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='specialties',
        ),
        migrations.CreateModel(
            name='ContractorPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.URLField(blank=True, default='', verbose_name='Banner')),
                ('biography', models.TextField(blank=True, default='', verbose_name='Biografia')),
                ('language', models.CharField(default='pt-BR', max_length=16, verbose_name='Idioma')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço mínimo')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço máximo')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço fixo')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('contractor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_portfolio', to=settings.AUTH_USER_MODEL, verbose_name='Contractor')),
            ],
            options={
                'verbose_name': 'Portfólio de Contratante',
                'verbose_name_plural': 'Portfólios de Contratante',
            },
        ),
    ]
