# Generated by Django 5.2.5 on 2025-09-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='https://www.youtube.com/shorts/uA9Zcg3vHvo', db_index=True),
            preserve_default=False,
        ),
    ]
