# Generated by Django 5.2.5 on 2025-10-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='categories',
        ),
    ]
