# Generated by Django 5.2.5 on 2025-09-12 11:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-id'], 'verbose_name': 'Vaga', 'verbose_name_plural': 'Vagas'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='example_video_urls',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location_mode',
        ),
        migrations.RemoveField(
            model_name='job',
            name='payment',
        ),
        migrations.AddField(
            model_name='job',
            name='fixed_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Pagamento fixo'),
        ),
        migrations.AddField(
            model_name='job',
            name='max_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Pagamento máximo'),
        ),
        migrations.AddField(
            model_name='job',
            name='min_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Pagamento mínimo'),
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('FIXED', 'Fixo'), ('FREELANCE', 'Freelance')], default='FIXED', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='video_example_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('REMOTE', 'Remoto'), ('ON_SITE', 'Presencial'), ('HYBRID', 'Híbrido')], default='REMOTE', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Contratante'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
