# Generated by Django 5.2.5 on 2025-10-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_categories_alter_job_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='categories',
        ),
    ]
